---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluentbit
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: 
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluentbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fluentbit
subjects:
  - kind: ServiceAccount
    name: fluentbit
---
apiVersion: v1
kind: Pod
metadata:
  name: fluent-bit-sumologic
  annotations:
    app: fluent-bit
spec:
  containers:
  - name: fluent-bit
    image: fluent-bit-sumologic:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
          cpu: 100m
          memory: 300Mi
    volumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
  serviceAccountName: fluentbit
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
